#!/usr/bin/env node
// Canvas paste kit for all three terms: one HTML body per Canvas entry, the
// rubric CSVs those entries use, and the syllabus, written to canvas-export/
// (gitignored). Entries come from each page's `assignment.canvas` frontmatter,
// expanded by src/lib/canvas-entries. Reads dist/, so run `npm run build`
// first. KIT_README below is what a body is and how the kit is laid out.
// --strict exits 1 on any warning, which is how CI catches an OVERRIDES entry
// whose page changed under it, or a page element the transform does not
// handle. A stopgap for #50 until #5 builds an .imscc.
//
// Run: npm run build && npm run canvas:export [-- --strict]
import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { fromHtml } from "hast-util-from-html";
import { minifyWhitespace } from "hast-util-minify-whitespace";
import { select, selectAll } from "hast-util-select";
import { toHtml } from "hast-util-to-html";
import { toString as text } from "hast-util-to-string";
import { h } from "hastscript";
import { SKIP, visit } from "unist-util-visit";
import { parse } from "yaml";
import { canvasRows, TERMS } from "../src/lib/canvas-entries.mjs";

const SITE = "https://capstone.alexulbrich.com";
const OUT = "canvas-export";
const PAGES = "src/content/docs/assignments";
const COURSE = { fall: "CS 461", spring: "CS 463", winter: "CS 462" };
const SYLLABUS = { fall: "cs461", spring: "cs463", winter: "cs462" };
// Built in Canvas by the co-instructor (#197); their weight is what the
// handbook's entries leave of the term's 100%.
const OWNED = {
  fall: "Resume and Intent",
  spring: "the Career and Individual Retrospective",
};
const TERM_WORD = /\b(fall|winter|spring)\b/gi;

const CELL =
  "border:1px solid #c7cdd1;padding:6px 8px;vertical-align:top;text-align:left;";
const BOX =
  "border:1px solid #c7cdd1;border-left:4px solid #2d3b45;border-radius:4px;padding:8px 12px;margin:12px 0;";

const SUBMISSION = {
  image: "a screenshot",
  none: "nothing to submit",
  pdf: "one PDF",
  survey: "a Qualtrics survey",
  text: "a short text entry",
  url: "a URL",
  video: "a video",
};

const KIT_README = `# Canvas Paste Kit

Generated by \`scripts/canvas-export.mjs\` and gitignored: edit the script, not this file. Stopgap for #50 until #5 generates an \`.imscc\`.

Regenerate after any handbook or rubric CSV change:

\`\`\`sh
npm run build
npm run canvas:export
\`\`\`

A \`WARN\` line means a page-specific cut in \`OVERRIDES\` no longer matches its page, or a page gained an element the transform does not handle; \`--strict\` turns either into a failure.

## Layout

\`fall/\`, \`winter/\`, \`spring/\`, each with:

- \`README.md\`: every Canvas entry with its group, points, weight, due week, submission type and rubric, plus the assignment-group weights. Generated; the entry list is the pages' \`assignment.canvas\` frontmatter.
- \`bodies/NN-<entry>.html\`: one body per entry, in due order. Paste into the assignment's HTML editor.
- \`rubrics/*-rubric.csv\`: byte-identical copies of the rubric CSVs that term's entries use, in Canvas's own import format (#284). Import each from the course's Rubrics page, then attach it to every entry the README lists against it.
- \`syllabus/cs46x.html\`: verbatim copy from \`canvas/syllabus/\`.

## What a body is

The handbook page for that entry, with:

- a link to the handbook page on top, then a Submission / Due / Weight box for this entry, replacing the page's own meta box and its Canvas-entries table;
- rubric tables removed, since Canvas shows the attached rubric below the body; prose under a rubric heading stays under **Grading**, an empty rubric heading goes;
- links made absolute, tabs reduced to this term's panel, math kept as MathML.

Then trimmed to the entry, by rules that read the page rather than name it:

1. A section headed by another entry's name goes: the RFC Final body drops "RFC Draft + Peer Review", a sprint note drops "Sprint Notes N: Individual Contribution", the Midterm Pulse section leaves the end-of-term survey.
2. A heading, aside title, table row's first cell, bold paragraph lead, or list item opening "In spring" that names only other terms goes. In a numbered family, a row or bold lead for another week goes too ("Fall, week 10" leaves Repo Checkpoint 1).
3. A section, row or paragraph naming another member of a numbered family goes ("### Workshop 4: ..." leaves Workshop 2).
4. A column headed by another term's course number goes ("CS 462" leaves the fall partner survey).

\`OVERRIDES\` in \`scripts/canvas-export.mjs\` holds the page-specific cuts no rule sees.

Mentions of other terms that remain are cross-term context a student needs ("Winter's instrumentation commitment comes due here").

## Not generated

- Resume and Intent (fall) and the Career and Individual Retrospective (spring) are the co-instructor's, in Canvas (#197).
- The letter-grade scale is a course setting: the scale in \`learning-objectives/grading.mdx\`.
`;

const warnings = [];
const cap = (s) => s[0].toUpperCase() + s.slice(1);
const pct = (n) => `${Number.parseFloat(n.toFixed(2))}%`;
const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
const isEl = (n) => n.type === "element";
const hasClass = (n, c) => (n.properties?.className ?? []).includes(c);
const termsIn = (s) =>
  [...s.matchAll(TERM_WORD)].map((m) => m[1].toLowerCase());
// Text mentions some term, but not this one: it belongs to another term.
const otherTerm = (s, term) => {
  const found = termsIn(s);
  return found.length > 0 && !found.includes(term);
};

// ---- entries -----------------------------------------------------------------

// Pages with no `assignment.canvas` block that still get a 0-point Canvas
// item (canvas/assignments/assignment-readme.md). resume-and-intent and
// career-retrospective are Canvas-owned (#197) and absent on purpose.
const ZERO_POINT = [
  {
    due: "Register by the end of fall week 3",
    name: "Demo Day Registration",
    page: "demo-day",
    submission: "Team; a screenshot of the registration confirmation",
    term: "fall",
    week: 3,
  },
  {
    due: "Spring, end of week 10",
    name: "Engineering Expo",
    page: "expo",
    submission: "Team; a short text entry",
    term: "spring",
    week: 10,
  },
];

function readPage(file) {
  const source = readFileSync(`${PAGES}/${file}`, "utf8");
  return parse(source.split(/^---$/m)[1]) ?? {};
}

function entries() {
  const all = [];
  for (const file of readdirSync(PAGES).filter((f) => f.endsWith(".mdx"))) {
    const data = readPage(file);
    const canvas = data.assignment?.canvas;
    if (!canvas) {
      continue;
    }
    const page = file.replace(/\.mdx$/, "");
    for (const row of canvasRows(canvas)) {
      row.weeks.forEach((week, i) => {
        all.push({
          families: canvas,
          family: row.family,
          level: data.assignment.level,
          name: row.names[i],
          page,
          term: row.term,
          week,
          weight: row.each,
        });
      });
    }
  }
  for (const z of ZERO_POINT) {
    all.push({ ...z, families: [], family: { name: z.name }, zero: true });
  }
  // Demo Day presenting is 1% extra credit in the term a team presents (#305),
  // outside the four components, so no frontmatter carries it.
  for (const term of TERMS) {
    all.push({
      extra: true,
      families: [],
      family: {
        group: "Extra Credit",
        name: "Demo Day Presentation",
        points: 100,
        submission: "none",
      },
      name: "Demo Day Presentation",
      page: "demo-day",
      term,
      week: term === "spring" ? 5 : 10,
      weight: 1,
    });
  }
  return all;
}

// ---- page-specific cuts no general rule covers ---------------------------------

const OVERRIDES = {
  "Midterm Pulse": (o) => {
    o.dropBlock("Fall and winter are progress-focused");
    o.dropBlock("The pulse has its own scale");
    for (const id of [
      "how-the-scoring-works",
      "reflection",
      "requirements-and-specifications",
      "design-implementation-and-deployment",
      "verification-and-validation",
      "teamwork",
      "communication",
      "individual-accountability",
    ]) {
      o.dropSection(id);
    }
  },
  // The audit is part of the fall week 5 gate only.
  "Repo Checkpoint {n}": (o, e) => {
    if (!(e.term === "fall" && e.week === 5)) {
      o.dropSection("the-inherited-codebase-audit");
    }
  },
  // The individual half has its own section; nothing else on the page is it.
  "Sprint Notes {n}: Individual Contribution": (o, e) => {
    o.keepOnly("sprint-notes-n-individual-contribution");
    o.renameHeading("sprint-notes-n-individual-contribution", e.name);
  },
};

// ---- trimming ------------------------------------------------------------------

// Index just past the section headed at top[i]: the next heading of the same
// or a higher level, or the end.
function sectionEnd(top, i) {
  const stops = top[i].tagName === "h2" ? ["h2"] : ["h2", top[i].tagName];
  let j = i + 1;
  while (j < top.length && !(isEl(top[j]) && stops.includes(top[j].tagName))) {
    j += 1;
  }
  return j;
}

function ops(root, where) {
  const top = root.children;
  const miss = (what) => warnings.push(`${where}: no match for ${what}`);
  const find = (id) => top.findIndex((n) => isEl(n) && n.properties.id === id);
  return {
    dropBlock(start, count = 1) {
      const i = top.findIndex(
        (n) => isEl(n) && text(n).trim().startsWith(start)
      );
      if (i < 0) {
        return miss(`block "${start}"`);
      }
      top.splice(i, count);
    },
    dropSection(id) {
      const i = find(id);
      if (i < 0) {
        return miss(`section #${id}`);
      }
      top.splice(i, sectionEnd(top, i) - i);
    },
    keepOnly(id) {
      const i = find(id);
      if (i < 0) {
        return miss(`section #${id}`);
      }
      top.splice(sectionEnd(top, i));
      top.splice(0, i);
    },
    renameHeading(id, label) {
      const i = find(id);
      if (i < 0) {
        return miss(`heading #${id}`);
      }
      top[i].children = [{ type: "text", value: label }];
    },
  };
}

// The heading text a family would give its own section: "Sprint Notes N".
const familyHeading = (f) => f.name.replace("{n}", "N");
const familyBase = (f) =>
  f.name.includes("{n}") ? f.name.slice(0, f.name.indexOf("{n}")) : null;

// An aside, table row, list item, or top-level paragraph about another term,
// another week, or another member of a numbered family.
function outOfScope(node, parent, { offTerm, otherMember, root, term }) {
  return (
    (hasClass(node, "starlight-aside") &&
      offTerm(text(select(".starlight-aside__title", node) ?? node))) ||
    (node.tagName === "tr" &&
      (() => {
        const first = node.children.find(isEl);
        const s = first ? text(first).trim() : "";
        return offTerm(s) || otherMember(s);
      })()) ||
    (node.tagName === "li" &&
      (() => {
        const m = text(node)
          .trim()
          .match(/^In (fall|winter|spring)\b/i);
        return Boolean(m && m[1].toLowerCase() !== term);
      })()) ||
    (node.tagName === "p" &&
      parent === root &&
      (() => {
        const s = text(node).trim();
        const lead = node.children.find(
          (c) => isEl(c) || (c.type === "text" && c.value.trim())
        );
        return (
          (lead?.tagName === "strong" && offTerm(text(lead))) || otherMember(s)
        );
      })())
  );
}

function dropOtherCourseColumns(root, term) {
  for (const table of selectAll("table", root)) {
    const head = select("tr", table)?.children.filter(isEl) ?? [];
    const off = head.map((c) => {
      const course = text(c).match(/CS 46[123]/);
      return course ? course[0] !== COURSE[term] : false;
    });
    if (off.some(Boolean)) {
      for (const tr of selectAll("tr", table)) {
        tr.children = tr.children.filter(isEl).filter((_, k) => !off[k]);
      }
    }
  }
}

function rubricHeadingsToGrading(top) {
  for (let i = 0; i < top.length; i += 1) {
    const n = top[i];
    const isRubric =
      isEl(n) &&
      ["h2", "h3"].includes(n.tagName) &&
      /^Rubric|\bRubric$/.test(text(n).trim());
    if (!isRubric) {
      continue;
    }
    const next = top[i + 1];
    if (!next || (isEl(next) && /^h[23]$/.test(next.tagName))) {
      top.splice(i, 1);
      i -= 1;
    } else {
      n.children = [{ type: "text", value: "Grading" }];
    }
  }
}

function trim(e, root) {
  const top = root.children;
  const { term, week, family } = e;
  const weeksInTerm = family.weeks?.[term]?.length ?? 1;

  // 1. Sections owned by another entry family on the same page. A heading
  // belongs to the family with the longest name it starts with.
  const owner = (heading) =>
    e.families
      .filter((f) => heading.startsWith(familyHeading(f)))
      .sort((a, b) => b.name.length - a.name.length)[0];
  // 2. Sections, asides, rows, bold-lead paragraphs about another term, or
  // another week of a numbered family ("Fall, week 10" in Repo Checkpoint 1).
  const offTerm = (s) => {
    if (otherTerm(s, term)) {
      return true;
    }
    const w = s.match(/^\W*(?:fall|winter|spring),? weeks? (\d+)\b/i);
    return Boolean(w && weeksInTerm > 1 && Number(w[1]) !== week);
  };
  // 3. Rows and paragraphs naming another member of a numbered family.
  const base = familyBase(family);
  const memberRe = base ? new RegExp(`^${base}(\\d+)\\b`) : null;
  const own = memberRe ? e.name.match(memberRe)?.[1] : null;
  const otherMember = (s) => {
    const m = memberRe ? s.match(memberRe) : null;
    return Boolean(m && m[1] !== own);
  };

  for (let i = 0; i < top.length; i += 1) {
    const n = top[i];
    if (!(isEl(n) && ["h2", "h3"].includes(n.tagName))) {
      continue;
    }
    const heading = text(n).trim();
    const f = n.tagName === "h2" ? owner(heading) : null;
    if ((f && f !== family) || offTerm(heading) || otherMember(heading)) {
      top.splice(i, sectionEnd(top, i) - i);
      i -= 1;
    }
  }

  const scope = { offTerm, otherMember, root, term };
  visit(root, "element", (node, index, parent) => {
    if (outOfScope(node, parent, scope)) {
      parent.children.splice(index, 1);
      return [SKIP, index];
    }
  });

  // 4. Columns headed by another term's course ("CS 462").
  dropOtherCourseColumns(root, term);

  OVERRIDES[family.name]?.(ops(root, `${term}/${e.name}`), e);

  // 5. Rubric headings: Canvas shows the attached rubric below the body, so
  // the table is gone. Keep the prose under "Grading", or drop an empty one.
  rubricHeadingsToGrading(top);
}

// ---- transform -------------------------------------------------------------------

function metaBox(e) {
  const row = (label, value) => [
    h("dt", { style: "font-weight:bold;" }, label),
    h("dd", { style: "margin:0 0 6px 0;" }, value),
  ];
  let submission;
  let due;
  let weight;
  if (e.zero) {
    ({ submission, due } = e);
    weight = "No points; it does not change your grade";
  } else if (e.extra) {
    submission = "Team; nothing to submit, your team presents at its session";
    due = "The Demo Day session your team registered for";
    weight = "1% extra credit in the term your team presents";
  } else {
    const kinds = [e.family.submission].flat();
    const who =
      e.level === "individual" || e.family.name.includes("Individual")
        ? "Individual"
        : "Team";
    submission =
      e.page === "project-partner-evaluation"
        ? "Completed by your project partner, not by you"
        : `${who}; ${kinds.map((k) => SUBMISSION[k] ?? k).join(" and ")}`;
    due = kinds.includes("survey")
      ? `${cap(e.term)}, closes end of week ${e.week}`
      : `${cap(e.term)}, week ${e.week}`;
    if (e.family.peer_review_week) {
      due += `; peer reviews end of week ${e.family.peer_review_week}`;
    }
    weight = `${pct(e.weight)} of the ${e.term} grade`;
  }
  return h("div", { style: BOX }, [
    h("dl", { style: "margin:0;" }, [
      ...row("Submission", submission),
      ...row("Due", due),
      ...row("Weight", weight),
    ]),
  ]);
}

function body(e) {
  const pageUrl = `${SITE}/assignments/${e.page}/`;
  const doc = fromHtml(
    readFileSync(`dist/assignments/${e.page}/index.html`, "utf8")
  );
  const root = select("div.sl-markdown-content", doc);
  if (!root) {
    throw new Error(`${e.page}: no .sl-markdown-content`);
  }

  // Tabs: keep the panel for this term, else show every panel under its label.
  visit(root, "element", (node, index, parent) => {
    if (node.tagName !== "starlight-tabs") {
      return;
    }
    const labels = selectAll('[role="tab"]', node).map((t) => text(t).trim());
    const panels = selectAll('[role="tabpanel"]', node);
    const k = labels.findIndex((l) => termsIn(l).includes(e.term));
    const flat =
      k >= 0
        ? panels[k].children
        : panels.flatMap((p, i) => [
            h("p", h("strong", labels[i])),
            ...p.children,
          ]);
    parent.children.splice(index, 1, ...flat);
    return [SKIP, index + flat.length];
  });

  // Code blocks: Expressive Code's frame, stylesheet link, token spans and
  // copy button become a plain <pre><code>, one line per source line.
  visit(root, "element", (node, index, parent) => {
    if (!hasClass(node, "expressive-code")) {
      return;
    }
    const lines = selectAll(".ec-line", node).map((l) => text(l));
    parent.children.splice(index, 1, h("pre", h("code", lines.join("\n"))));
    return [SKIP, index + 1];
  });

  // Drop what Canvas cannot use, the page's own meta and entry tables, and
  // the rubric tables; unwrap Starlight's heading wrapper.
  visit(root, "element", (node, index, parent) => {
    const drop =
      ["script", "style", "svg", "starlight-tabs-restore"].includes(
        node.tagName
      ) ||
      [
        "sl-anchor-link",
        "katex-html",
        "rubric",
        "assignment-meta",
        "canvas-entries",
      ].some((c) => hasClass(node, c));
    if (drop) {
      parent.children.splice(index, 1);
      return [SKIP, index];
    }
    if (hasClass(node, "sl-heading-wrapper")) {
      parent.children.splice(index, 1, ...node.children);
      return [SKIP, index];
    }
  });
  root.children = root.children.filter(
    (n) => !(n.type === "text" && !n.value.trim())
  );

  trim(e, root);

  visit(root, "element", (node) => {
    const p = node.properties;
    const style = (s) => {
      p.style = `${p.style ?? ""}${s}`;
    };
    if (hasClass(node, "starlight-aside")) {
      style(BOX);
      p.ariaLabel = undefined;
    }
    if (hasClass(node, "starlight-aside__title")) {
      style("font-weight:bold;margin-top:0;");
      p.ariaHidden = undefined;
    }
    if (node.tagName === "table") {
      style("border-collapse:collapse;width:100%;margin:12px 0;");
    }
    if (node.tagName === "th" || node.tagName === "td") {
      style(CELL);
    }
    for (const attr of ["href", "src"]) {
      const v = p[attr];
      if (typeof v === "string" && v.startsWith("/")) {
        p[attr] = SITE + v;
      } else if (typeof v === "string" && v.startsWith("#")) {
        p[attr] = pageUrl + v;
      }
    }
    p.className = undefined;
    p.dir = undefined;
    p.dataPagefindIgnore = undefined;
  });

  visit(root, "element", (node) => {
    if (
      node.tagName.includes("-") ||
      ["iframe", "img", "video", "details", "form", "button"].includes(
        node.tagName
      )
    ) {
      warnings.push(`${e.term}/${e.name}: unhandled <${node.tagName}>`);
    }
  });

  // A link only: once pasted, Canvas is authoritative (AGENTS.md hard rule 7).
  const source = h("p", [
    "Handbook page: ",
    h("a", { href: pageUrl }, text(select("h1", doc)).trim()),
  ]);
  return canvasHtml({
    children: [source, metaBox(e), ...root.children],
    type: "root",
  });
}

// Canvas's editor breaks on a tag split across lines ("</a\n  >") and on
// multi-line style attributes, which a code formatter produces. Re-serialize:
// whole tags, one-line styles, collapsed whitespace, one line per block.
function canvasHtml(tree) {
  visit(tree, "element", (node) => {
    const { style } = node.properties;
    if (typeof style === "string") {
      node.properties.style = style
        .split(";")
        .map((d) => d.replace(/\s+/g, " ").trim())
        .filter(Boolean)
        .join("; ");
    }
  });
  minifyWhitespace(tree);
  return `${tree.children.map((n) => toHtml(n)).join("\n")}\n`;
}

// ---- output ----------------------------------------------------------------------

function termReadme(term, list) {
  const groups = new Map();
  for (const e of list.filter((x) => !(x.zero || x.extra))) {
    groups.set(e.family.group, (groups.get(e.family.group) ?? 0) + e.weight);
  }
  const total = [...groups.values()].reduce((a, b) => a + b, 0);
  const extra = list
    .filter((x) => x.extra)
    .reduce((sum, x) => sum + x.weight, 0);
  const rows = list.map((e) =>
    [
      e.file.slice(0, 2),
      e.name,
      e.zero ? "none (0 points, omit from final grade)" : e.family.group,
      e.zero ? 0 : e.family.points,
      e.zero ? "" : pct(e.weight),
      e.week +
        (e.family.peer_review_week
          ? `, reviews ${e.family.peer_review_week}`
          : ""),
      e.zero ? "" : [e.family.submission].flat().join(", "),
      e.family.rubric ? `\`${e.family.rubric.split("/")[1]}\`` : "none",
    ].join(" | ")
  );
  return `# ${cap(term)} (${COURSE[term]})

Generated by \`scripts/canvas-export.mjs\`; do not edit by hand.

## Canvas entries

| # | Entry | Group | Points | Weight | Due week | Submission | Rubric |
|---|---|---|---|---|---|---|---|
${rows.map((r) => `| ${r} |`).join("\n")}

## Assignment group weights

| Group | Weight |
|---|---|
${[...groups].map(([g, w]) => `| ${g} | ${pct(w)} |`).join("\n")}
| **Total** | **${pct(total)}** |
| Extra Credit (on top of the total) | ${pct(extra)} |
${OWNED[term] ? `\nThe rest of the term is ${OWNED[term]} (${pct(100 - total)}), built in Canvas by the co-instructor (#197); nothing for it here.\n` : ""}`;
}

const all = entries();
for (const term of TERMS) {
  rmSync(`${OUT}/${term}`, { force: true, recursive: true });
  for (const d of ["bodies", "rubrics", "syllabus"]) {
    mkdirSync(`${OUT}/${term}/${d}`, { recursive: true });
  }
  const list = all
    .filter((e) => e.term === term)
    .sort((a, b) => a.week - b.week);
  const count = (n) => list.filter((x) => x.name === n).length;
  list.forEach((e, i) => {
    const label = count(e.name) > 1 ? `${e.family.group} ${e.name}` : e.name;
    e.file = `${String(i + 1).padStart(2, "0")}-${slug(label)}.html`;
    writeFileSync(`${OUT}/${term}/bodies/${e.file}`, body(e));
  });
  const rubrics = new Set(list.map((e) => e.family.rubric).filter(Boolean));
  for (const r of rubrics) {
    copyFileSync(
      `canvas/assignments/${r}`,
      `${OUT}/${term}/rubrics/${r.split("/")[1]}`
    );
  }
  writeFileSync(
    `${OUT}/${term}/syllabus/${SYLLABUS[term]}.html`,
    canvasHtml(
      fromHtml(readFileSync(`canvas/syllabus/${SYLLABUS[term]}.html`, "utf8"), {
        fragment: true,
      })
    )
  );
  writeFileSync(`${OUT}/${term}/README.md`, termReadme(term, list));
  console.log(`${term}: ${list.length} bodies, ${rubrics.size} rubrics`);
}
writeFileSync(`${OUT}/README.md`, KIT_README);
for (const w of warnings) {
  console.warn(`WARN ${w}`);
}
if (warnings.length > 0 && process.argv.includes("--strict")) {
  process.exit(1);
}
